# Welcome to Jekyll!
title: Diego S.C.
email: diegosc@protonmail.com
description:
  en: I'm a software, web and musician (why not) developer in new things.
  pt: Sou dev de software, web e músico (por que não) em coisas novas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://diegosc.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Di_Will
github_username:  diegosozua
linkedin_username: disouzacosta
facebook_username: SouzaDiego

permalink: /:title

#Header translation
article:
  en: Articles
  pt: Artigos
info: Info
idiom:
  en: Idioms
  pt: Idiomas

#Indexing through the pages
i:
  en:
    index: /
    article: /articles
    about: /about
  pt:
    index: /indice.html
    article: /artigos.html
    about: /sobre.html

#Articles loop
a:
  en:
    more: More
  pt:
    more: Mais

#Read more
e:
  en:
    read: Read more
  pt:
    read: Leia mais

#reading time
r:
  en:
    minute: minute
    minutes: minutes
    read: read
  pt:
    minute: minuto
    minutes: minutos
    read: de leitura

#Footer translation
made:
  en: Made with
  pt: Feito com
back:
  en: Back to Top
  pt: Voltar ao Topo

# Share
s:
  en:
    share: Share this on
  pt:
    share: Compartilhe

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
